### ISSUE TITLE
History changed locally but not on github after pushing

### ISSUE THREAD

**Issue by chonga802** [davidfokkema/git-rewrite-author#9]
I did git push --force but my online github repo history did not get updated. I did this to a forked repo. Does that matter?

**Comment by chonga802** [comment]
Nevermind, it just took github like an hour to update.

**Comment by davidfokkema** [comment]
Ok, GitHub had a few problems yesterday. Maybe that's why it took so long. If something like this ever happens again, you can always check http://status.github.com/. Maybe you did already. Older messages can be viewed on https://status.github.com/messages, and I see quite a few issues cropping up yesterday.
